/**
 * Site generator — produces static HTML/CSS/JS for a generated demo site.
 *
 * This module is deterministic by design. It takes a website brief plus the
 * canonical lead data and writes a small static site (index.html, styles.css,
 * script.js, vercel.json, README.md) into the GENERATED_SITES_DIR.
 *
 * The deterministic generator is the production path for MVP — it produces
 * predictable, on-brand output without depending on the AI gateway. The AI
 * gateway is used for the brief and for optional copy refinement, but the HTML
 * skeleton is rendered server-side from the brief so generation cannot fail
 * because of a malformed model response.
 */
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { env } from '../lib/env.js';
import type { WebsiteBrief } from '../schemas/index.js';

export interface SiteGenerationInput {
  leadId: string;
  generatedSiteId: string;
  brief: WebsiteBrief;
  lead: {
    businessName: string;
    category: string | null;
    addressLine1: string | null;
    city: string | null;
    postcode: string | null;
    country: string | null;
    phone: string | null;
    existingWebsiteUrl: string | null;
  };
  /**
   * Pre-generated HTML from the AI model rotation.
   * When provided, replaces the deterministic renderer.
   * Falls back to deterministic if this is absent or empty.
   */
  preGeneratedHtml?: string;
  /**
   * Images generated by the image rotation (Pollinations.ai).
   * Written as binary files alongside index.html before upload.
   */
  preGeneratedImages?: Array<{ filename: string; data: Buffer }>;
}

export interface SiteGenerationResult {
  outputDir: string;
  files: string[];
  title: string;
  summary: string;
  /** Whether HTML came from AI generation or the deterministic fallback. */
  htmlSource: 'ai' | 'deterministic';
}

const escape = (s: string) =>
  s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');

function renderHtml(b: WebsiteBrief, lead: SiteGenerationInput['lead']): string {
  const fullAddress = [lead.addressLine1, lead.city, lead.postcode, lead.country]
    .filter(Boolean)
    .join(', ');
  const sectionsHtml = b.sections
    .map(
      (s, i) => `
      <section class="section" id="section-${i + 1}">
        <h2>${escape(s.title)}</h2>
        <p class="purpose">${escape(s.purpose)}</p>
        <p>${escape(s.contentNotes)}</p>
      </section>`,
    )
    .join('\n');

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>${escape(b.businessName)} — ${escape(b.businessCategory)}</title>
  <meta name="description" content="${escape(b.targetCustomer)}" />
  <link rel="stylesheet" href="styles.css" />
</head>
<body>
  <header class="hero">
    <div class="container">
      <p class="eyebrow">${escape(b.businessCategory)}${lead.city ? ` · ${escape(lead.city)}` : ''}</p>
      <h1>${escape(b.businessName)}</h1>
      <p class="lede">${escape(b.targetCustomer)}</p>
      <div class="cta-row">
        ${lead.phone ? `<a class="cta primary" href="tel:${escape(lead.phone)}">${escape(b.primaryCTA)}</a>` : `<a class="cta primary" href="#contact">${escape(b.primaryCTA)}</a>`}
        <a class="cta ghost" href="#contact">Get in touch</a>
      </div>
    </div>
  </header>

  <main class="container">
    ${sectionsHtml}

    <section class="section" id="contact">
      <h2>Contact</h2>
      <ul class="contact-list">
        ${lead.phone ? `<li><strong>Phone:</strong> <a href="tel:${escape(lead.phone)}">${escape(lead.phone)}</a></li>` : ''}
        ${fullAddress ? `<li><strong>Address:</strong> ${escape(fullAddress)}</li>` : ''}
        ${lead.existingWebsiteUrl ? `<li><strong>Existing site:</strong> <a href="${escape(lead.existingWebsiteUrl)}" rel="noopener">${escape(lead.existingWebsiteUrl)}</a></li>` : ''}
      </ul>
    </section>
  </main>

  <footer>
    <div class="container">
      <p>This is a demo concept generated as part of an outreach proposal. Not affiliated with the business.</p>
    </div>
  </footer>
  <script src="script.js"></script>
</body>
</html>
`;
}

function renderCss(brief: WebsiteBrief): string {
  // Deterministic palette derived from the brief's colourDirection text.
  const palette = pickPalette(brief.colourDirection);
  return `:root {
  --bg: ${palette.bg};
  --fg: ${palette.fg};
  --muted: ${palette.muted};
  --accent: ${palette.accent};
  --accent-fg: ${palette.accentFg};
  --line: ${palette.line};
}
* { box-sizing: border-box; }
html, body { margin: 0; padding: 0; }
body {
  font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, Inter, sans-serif;
  color: var(--fg);
  background: var(--bg);
  line-height: 1.55;
}
.container { max-width: 1080px; margin: 0 auto; padding: 0 24px; }
.hero { padding: 96px 0 64px; border-bottom: 1px solid var(--line); }
.eyebrow { letter-spacing: 0.16em; text-transform: uppercase; font-size: 12px; color: var(--muted); margin: 0 0 12px; }
h1 { font-size: clamp(34px, 5vw, 56px); margin: 0 0 16px; line-height: 1.05; letter-spacing: -0.01em; }
.lede { font-size: 18px; color: var(--muted); max-width: 60ch; }
.cta-row { display: flex; gap: 12px; margin-top: 28px; flex-wrap: wrap; }
.cta { display: inline-flex; align-items: center; padding: 12px 20px; border-radius: 8px; text-decoration: none; font-weight: 600; }
.cta.primary { background: var(--accent); color: var(--accent-fg); }
.cta.ghost { border: 1px solid var(--line); color: var(--fg); }
.section { padding: 56px 0; border-bottom: 1px solid var(--line); }
.section h2 { margin: 0 0 12px; font-size: 26px; letter-spacing: -0.005em; }
.section .purpose { color: var(--muted); margin: 0 0 12px; font-size: 14px; }
.contact-list { list-style: none; padding: 0; margin: 0; display: grid; gap: 8px; }
footer { padding: 32px 0; color: var(--muted); font-size: 13px; }
@media (max-width: 600px) {
  .hero { padding: 64px 0 40px; }
}
`;
}

function pickPalette(direction: string) {
  const lower = direction.toLowerCase();
  if (lower.includes('dark') || lower.includes('night')) {
    return { bg: '#0b0d12', fg: '#e8ecf4', muted: '#8a93a8', accent: '#7cf0a8', accentFg: '#0b0d12', line: '#1a1d27' };
  }
  if (lower.includes('warm') || lower.includes('earth') || lower.includes('cream')) {
    return { bg: '#fbf7f0', fg: '#2a2620', muted: '#7a6f5c', accent: '#c0653a', accentFg: '#ffffff', line: '#ece4d4' };
  }
  if (lower.includes('blue') || lower.includes('navy') || lower.includes('finance')) {
    return { bg: '#f5f7fb', fg: '#10182a', muted: '#5b6479', accent: '#1c4cd9', accentFg: '#ffffff', line: '#e3e8f1' };
  }
  return { bg: '#ffffff', fg: '#0e1320', muted: '#566075', accent: '#0a8f5c', accentFg: '#ffffff', line: '#e7eaf0' };
}

const SCRIPT_JS = `// Smooth-scroll in-page anchors
document.querySelectorAll('a[href^="#"]').forEach((a) => {
  a.addEventListener('click', (e) => {
    const id = a.getAttribute('href').slice(1);
    const target = document.getElementById(id);
    if (target) {
      e.preventDefault();
      target.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  });
});
`;

const VERCEL_JSON = JSON.stringify({ cleanUrls: true, trailingSlash: false }, null, 2);

function buildFallbackGallery(brief: WebsiteBrief): string {
  return [
    '<!doctype html>',
    '<html lang="en">',
    '<head>',
    '  <meta charset="utf-8">',
    '  <meta name="viewport" content="width=device-width,initial-scale=1">',
    `  <title>${brief.businessName} — Gallery</title>`,
    '  <style>',
    '    body{font-family:system-ui,sans-serif;max-width:860px;margin:4rem auto;padding:0 1.5rem;line-height:1.6;color:#1a1a2e}',
    '    a{color:inherit;text-decoration:none;font-weight:600}',
    '    a:hover{text-decoration:underline}',
    '    .back{display:inline-flex;align-items:center;gap:0.4rem;margin-bottom:2.5rem;opacity:0.65;font-size:0.9rem}',
    '    h1{font-size:clamp(2rem,5vw,3rem);margin:0 0 0.5rem}',
    '    p{color:#555;margin:0 0 2rem}',
    '    .demo-disclaimer{font-size:0.75rem;opacity:0.5;margin-top:3rem}',
    '  </style>',
    '</head>',
    '<body>',
    '  <a class="back" href="index.html">← Back to main site</a>',
    `  <h1>${brief.businessName} — Work Gallery</h1>`,
    '  <p>Gallery coming soon.</p>',
    '  <p class="demo-disclaimer">This is a demo concept generated as part of an outreach proposal. Not affiliated with the business.</p>',
    '</body>',
    '</html>',
  ].join('\n');
}

export async function writeGeneratedSite(input: SiteGenerationInput): Promise<SiteGenerationResult> {
  const dir = path.join(env.GENERATED_SITES_DIR, input.leadId, input.generatedSiteId);

  try {
    await fs.mkdir(dir, { recursive: true });
  } catch (err) {
    throw new Error(`Failed to create site directory ${dir}: ${err instanceof Error ? err.message : err}`);
  }

  const readme = `# Generated demo site

Lead: ${input.lead.businessName}
Generated site id: ${input.generatedSiteId}

This bundle is deployed to Vercel by the lead panel. It is a static, single-page demo concept.
`;

  let files: Array<[string, string]>;
  let htmlSource: SiteGenerationResult['htmlSource'];

  if (input.preGeneratedHtml) {
    // AI-generated: model outputs index.html + gallery.html separated by ===GALLERY===
    htmlSource = 'ai';

    const GALLERY_DELIMITER = '===GALLERY===';
    const delimIdx = input.preGeneratedHtml.indexOf(GALLERY_DELIMITER);

    let indexHtml: string;
    let galleryHtml: string;

    if (delimIdx !== -1) {
      indexHtml = input.preGeneratedHtml.slice(0, delimIdx).trim();
      galleryHtml = input.preGeneratedHtml.slice(delimIdx + GALLERY_DELIMITER.length).trim();
    } else {
      indexHtml = input.preGeneratedHtml.trim();
      galleryHtml = buildFallbackGallery(input.brief);
    }

    files = [
      ['index.html', indexHtml],
      ['gallery.html', galleryHtml],
      ['vercel.json', VERCEL_JSON],
      ['README.md', readme],
    ];
  } else {
    // Deterministic fallback: separate CSS and JS files.
    htmlSource = 'deterministic';
    files = [
      ['index.html', renderHtml(input.brief, input.lead)],
      ['styles.css', renderCss(input.brief)],
      ['script.js', SCRIPT_JS],
      ['vercel.json', VERCEL_JSON],
      ['README.md', readme],
    ];
  }

  try {
    for (const [name, content] of files) {
      await fs.writeFile(path.join(dir, name), content, 'utf8');
    }
    for (const img of input.preGeneratedImages ?? []) {
      await fs.writeFile(path.join(dir, img.filename), img.data);
    }
  } catch (err) {
    throw new Error(`Failed to write site files to ${dir}: ${err instanceof Error ? err.message : err}`);
  }

  const allFiles = [
    ...files.map(([name]) => name),
    ...(input.preGeneratedImages ?? []).map((img) => img.filename),
  ];

  return {
    outputDir: dir,
    files: allFiles,
    title: `${input.brief.businessName} — ${input.brief.businessCategory}`,
    summary: input.brief.targetCustomer,
    htmlSource,
  };
}
